Repository pylhc/pylhc.github.io, pull requests merged in 2020-12, with the labels that each got.

#27 Add Creation of virtual enviroments to How-to
  docs/packages/development/howto_venv.md
  mkdocs.yml
Labels: enhancement, how-to

#30 #29 Add a "How to edit/add a Wiki page" page
  README.md
  docs/resources/howto/teleworking.md
  docs/resources/howto/wiki.md
  mkdocs.yml
Labels: documentation, enhancement, how-to

#31 Complete publication list
  docs/resources/publications.md
Labels: citation, enhancement

#37 Fix 2020 Pulication Titles
  docs/resources/howto/wiki.md
  docs/resources/publications.md
Labels: documentation

#34 Adding a description of K-Modulation to OMC methods page
  docs/omc_team/about.md
  docs/omc_team/ideas.md
  docs/omc_team/methods.md
  docs/omc_team/physics.md
  docs/packages/about.md
  docs/packages/development/contributing.md
  docs/packages/development/howto_release.md
  docs/packages/omc3/about.md
  docs/packages/omc3/getting_started.md
  docs/packages/omc3/workflow.md
  docs/procedures/ampdet.md
  docs/procedures/info.md
  docs/procedures/kmod.md
  docs/resources/howto/setup.md
  docs/resources/howto/teleworking.md
  docs/resources/howto/wiki.md
  docs/resources/links.md
Labels: documentation, enhancement

#38 Basic Error Propagation
  docs/omc_team/physics.md
Labels: enhancement
