Repository pylhc/pylhc.github.io, pull requests merged in 2020-11, with the labels that each got.

#9 Kmod procedure
  docs/css/extra.css
  docs/guis/betabeat/basics.md
  docs/guis/betabeat/beam_selection.md
  docs/guis/betabeat/gui.md
  docs/guis/betabeat/running.md
  docs/guis/kmod/basics.md
  docs/guis/kmod/gui.md
  docs/guis/multiturn/running.md
  docs/omc_team/publications.md
  docs/procedures/kmod.md
  docs/resources/howto/setup.md
  docs/resources/links.md
  docs/resources/publications.md
  mkdocs.yml
  snippets/running_guis.md
Labels: documentation, how-to

#10 Gitlab2AFS CI
  docs/resources/howto/setup.md
Labels: documentation, how-to

#11 Darkmode + Code Fixes in CSS
  docs/css/extra.css
  mkdocs.yml
Labels: bug, documentation, enhancement

#19 Python packages tab landing page
  docs/packages/about.md
  mkdocs.yml
Labels: documentation, enhancement

#22 Feature/18/package pages
  docs/assets/images/job_submitter/tune_sweep_condor_q.png
  docs/index.md
  docs/packages/about.md
  docs/packages/betabeatsrc.md
  docs/packages/development.md
  docs/packages/development/contributing.md
  docs/packages/development/howto_release.md
  docs/packages/generic_parser.md
  docs/packages/mess.md
  docs/packages/mess/about.md
  docs/packages/omc3/workflow.md
  docs/packages/pylhc.md
  docs/packages/pylhc/about.md
  docs/packages/pylhc/bsrt.md
  docs/packages/pylhc/forced_da.md
  docs/packages/pylhc/job_submitter.md
  docs/packages/pylhc/machine_settings_info.md
  docs/packages/sdds.md
  docs/packages/tfs-pandas.md
  mkdocs.yml
Labels: documentation, enhancement

#16 [HOLD] Refactor for ownership transfer
  LICENSE
  README.md
  docs/assets/images/job_submitter/tune_sweep_condor_q.png
  docs/omc_team/about.md
  docs/omc_team/ideas.md
  docs/packages/about.md
  docs/packages/betabeatsrc.md
  docs/packages/development.md
  docs/packages/development/contributing.md
  docs/packages/development/howto_release.md
  docs/packages/generic_parser.md
  docs/packages/mess.md
  docs/packages/mess/about.md
  docs/packages/omc3/about.md
  docs/packages/omc3/workflow.md
  docs/packages/pylhc.md
  docs/packages/pylhc/about.md
  docs/packages/pylhc/bsrt.md
  docs/packages/pylhc/forced_da.md
  docs/packages/pylhc/job_submitter.md
  docs/packages/pylhc/machine_settings_info.md
  docs/packages/sdds.md
  docs/packages/tfs-pandas.md
  docs/resources/publications.md
  mkdocs.yml
Labels: documentation, enhancement
