Repository pylhc/pylhc.github.io, pull requests merged in 2022-09, with the labels that each got.

#82 Summary Table and Packages Table update
  docs/css/hint.min.css
  docs/javascripts/config.js
  docs/javascripts/tablesort.js
  docs/packages/about.md
  docs/resources/computing.md
  docs/resources/logbook/2022_lhc.md
  docs/resources/publications.md
  mkdocs.yml
Labels: documentation

#83 CI Updates
  .github/workflows/documentation.yml
  .github/workflows/test_build.yml
  requirements.txt
Labels: CI/CD

#86 moved package table up
  docs/packages/about.md
Labels: enhancement
