Repository pylhc/pylhc.github.io, pull requests merged in 2022-05, with the labels that each got.

#72 Update Python ecosystem for kickgroups
  docs/packages/irnl/about.md
  docs/packages/pylhc/about.md
  docs/packages/pylhc/irnl_correction.md
  docs/packages/pylhc/kickgroups.md
  mkdocs.yml
Labels: enhancement

#74 Additional info and LSA knobs for RWS procedure
  docs/measurements/procedures/rigid_waist_shift.md
Labels: documentation, enhancement

#79 Add Beam setup flag check
  docs/measurements/procedures/general_checks.md
Labels: documentation, enhancement

#80 Additional info in RWS Procedure
  docs/measurements/procedures/rigid_waist_shift.md
Labels: documentation, enhancement, MDs
