Repository pylhc/pylhc.github.io, pull requests merged in 2024-10, with the labels that each got.

#145 Added MDs and Commissioning: Aug. and Sept. 2024
  docs/resources/logbook/2024_lhc.md
Labels: Type: Documentation, Estimate: Easy, Priority: Medium, Status: Review Needed

#146 Entry for MD13883: Optics with HV crossing plane
  docs/resources/logbook/2024_lhc.md
Labels: Type: Documentation, Priority: Medium

#147 Added new publications
  docs/resources/logbook/2024_lhc.md
  docs/resources/publications.md
  scripts/bib2md.py
Labels: Type: Documentation, Estimate: Easy, Priority: Low, Status: Review Needed
