Repository pylhc/pylhc.github.io, pull requests merged in 2025-09, with the labels that each got.

#198 User Guide Updates: BBGui - Analysis Panel
  docs/assets/images/analysis_panel_cleaning.png
  docs/assets/images/betabeat_gui/analysis_panel.png
  docs/assets/images/betabeat_gui/analysis_panel_frequency.png
  docs/assets/images/betabeat_gui/analysis_panel_frequency_controls_chart_options.png
  docs/assets/images/betabeat_gui/analysis_panel_frequency_controls_nattune.png
  docs/assets/images/betabeat_gui/analysis_panel_frequency_controls_resonance_lines.png
  docs/assets/images/betabeat_gui/analysis_panel_frequency_export.png
  docs/assets/images/betabeat_gui/analysis_panel_frequency_m1Qx_p2Qy_line.png
  docs/assets/images/betabeat_gui/analysis_panel_frequency_manual_line.png
  docs/assets/images/betabeat_gui/analysis_panel_frequency_manual_line_show.png
  docs/assets/images/betabeat_gui/analysis_panel_frequency_nattune.png
  docs/assets/images/betabeat_gui/analysis_panel_table.png
  docs/assets/images/betabeat_gui/analysis_panel_time_space.png
  docs/assets/images/betabeat_gui/analysis_panel_time_space_clean.png
  docs/assets/images/betabeat_gui/analysis_panel_time_space_manual_clean_after.png
  docs/assets/images/betabeat_gui/analysis_panel_time_space_manual_clean_before.png
  docs/assets/images/betabeat_gui/analysis_spectrum.png
  docs/assets/images/betabeat_gui/analysis_timespace.png
  docs/assets/images/betabeat_gui/do_optics_dialog.png
  docs/assets/images/betabeat_gui/do_optics_dialog_settings.png
  docs/assets/images/cleaning_settings.png
  docs/guis/betabeat/analysis_panel.md
  docs/guis/betabeat/bpm_panel.md
  docs/guis/betabeat/correction_panel.md
  docs/guis/betabeat/settings.md
  docs/guis/usage/guidelines.md
  docs/measurements/physics/optics.md
  mkdocs.yml
Labels: Type: Documentation, Priority: Medium, Estimate: Normal

#203 Update 2025_lhc.md
  docs/logbook/LHC/2025_lhc.md
Labels: Type: Documentation

#206 User guide updates temp warnings
  docs/css/extra.css
  docs/guis/betabeat/ampdet.md
  docs/guis/betabeat/correction_panel.md
  docs/guis/betabeat/optics_panel.md
Labels: Type: Documentation, Priority: Medium
