Repository pylhc/pylhc.github.io, pull requests merged in 2025-05, with the labels that each got.

#174 LHC logbook 2025-05-07
  docs/logbook/LHC/2025_lhc.md
Labels: Type: Documentation

#175 Moved
  docs/guis/developing/releases.md
  docs/guis/usage/ide_install.md
  docs/guis/usage/kmod_special.md
  docs/guis/usage/releases.md
  docs/guis/usage/remote.md
  docs/howto/about.md
  docs/packages/development/howto_venv.md
  docs/resources/git_setup.md
  docs/resources/remote_access.md
  docs/resources/shared_filesystems.md
  docs/resources/wiki.md
  mkdocs.yml
Labels: Type: Documentation, Type: Maintenance

#178 BBGui pics
  docs/assets/images/betabeat_gui/analysis_spectrum.png
  docs/assets/images/betabeat_gui/analysis_timespace.png
  docs/assets/images/betabeat_gui/bpm_panel.png
  docs/assets/images/betabeat_gui/corrections_correction_test.png
  docs/assets/images/betabeat_gui/corrections_global_window.png
  docs/assets/images/betabeat_gui/corrections_knob_panel.png
  docs/assets/images/betabeat_gui/corrections_strengths.png
  docs/assets/images/betabeat_gui/header.png
  docs/assets/images/betabeat_gui/model_creation_lhc.png
  docs/assets/images/betabeat_gui/model_creation_window.png
  docs/assets/images/betabeat_gui/model_creation_with_model.png
  docs/assets/images/betabeat_gui/open_files.png
  docs/assets/images/betabeat_gui/open_files_folders.png
  docs/assets/images/betabeat_gui/optics_action_tune.png
  docs/assets/images/betabeat_gui/optics_logbook_entry_window.png
  docs/assets/images/betabeat_gui/optics_panel.png
  docs/assets/images/betabeat_gui/optics_plot_export.png
  docs/assets/images/betabeat_gui/settings_accelerator.png
  docs/assets/images/betabeat_gui/settings_cleaning.png
  docs/assets/images/betabeat_gui/settings_gui.png
  docs/assets/images/betabeat_gui/settings_harpy.png
  docs/assets/images/betabeat_gui/settings_optics.png
  docs/assets/images/betabeat_gui/settings_tunes.png
Labels: Type: Documentation

#180 Chroma GUI Page
  docs/assets/images/chroma_gui/chromaticity_tab.png
  docs/assets/images/chroma_gui/cleaning_tab_cleaned_data.png
  docs/assets/images/chroma_gui/cleaning_tab_raw_data.png
  docs/assets/images/chroma_gui/corrections_tab.png
  docs/assets/images/chroma_gui/default_view.png
  docs/assets/images/chroma_gui/new_analysis_menu.png
  docs/assets/images/chroma_gui/plot_extracted_data.png
  docs/guis/about.md
  docs/guis/chroma/gui.md
  docs/resources/publications.md
  mkdocs.yml
  requirements.txt
Labels: Type: Documentation, Domain: GUI, Priority: Medium, Estimate: Normal, Status: Review Needed
